import { defineConfig } from 'tsup';

// theme.css itself is not a tsup entry — it's generated by tokens/generate.ts
// and copied to dist/ by this package's `build` script (see package.json).
export default defineConfig((options) => ({
  entry: {
    index: 'src/index.ts',
    'button/index': 'src/actions/button/index.ts',
    'input/index': 'src/forms/input/index.ts',
    'card/index': 'src/data-display/card/index.ts',
    'badge/index': 'src/data-display/badge/index.ts',
    'alert/index': 'src/feedback/alert/index.ts',
    'alert-popup/index': 'src/feedback/alert-popup/index.ts',
    'avatar/index': 'src/data-display/avatar/index.ts',
    'backdrop/index': 'src/overlays/backdrop/index.ts',
    'separator/index': 'src/layout/separator/index.ts',
    'accordion/index': 'src/data-display/accordion/index.ts',
    'dialog/index': 'src/overlays/dialog/index.ts',
    'popover/index': 'src/overlays/popover/index.ts',
    'tooltip/index': 'src/overlays/tooltip/index.ts',
    'tabs/index': 'src/navigation/tabs/index.ts',
    'checkbox/index': 'src/forms/checkbox/index.ts',
    'switch/index': 'src/forms/switch/index.ts',
    'radio-group/index': 'src/forms/radio-group/index.ts',
    'progress/index': 'src/feedback/progress/index.ts',
    'spinner/index': 'src/feedback/spinner/index.ts',
    'skeleton/index': 'src/feedback/skeleton/index.ts',
    'tokens/index': 'src/tokens/index.ts',
    'theme-provider/index': 'src/theming/theme-provider/index.ts',
    'theme-switcher/index': 'src/theming/theme-switcher/index.ts',
    'pagination/index': 'src/navigation/pagination/index.ts',
    'stepper/index': 'src/navigation/stepper/index.ts',
    'tree/index': 'src/data-display/tree/index.ts',
    'navigation-menu/index': 'src/navigation/navigation-menu/index.ts',
    'drawer/index': 'src/overlays/drawer/index.ts',
    'hover-card/index': 'src/overlays/hover-card/index.ts',
    'toast/index': 'src/feedback/toast/index.ts',
    'tree-view/index': 'src/data-display/tree-view/index.ts',
    'command/index': 'src/overlays/command/index.ts',
    'carousel/index': 'src/data-display/carousel/index.ts',
    'data-table/index': 'src/data-display/data-table/index.ts',
    'draggable/index': 'src/drag-and-drop/draggable/index.ts',
    'droppable/index': 'src/drag-and-drop/droppable/index.ts',
    'sortable/index': 'src/drag-and-drop/sortable/index.ts',
    'select/index': 'src/forms/select/index.ts',
    'combobox/index': 'src/forms/combobox/index.ts',
    'autocomplete/index': 'src/forms/autocomplete/index.ts',
    'menu/index': 'src/overlays/menu/index.ts',
    'dropdown-menu/index': 'src/overlays/dropdown-menu/index.ts',
    'context-menu/index': 'src/overlays/context-menu/index.ts',
    'menubar/index': 'src/overlays/menubar/index.ts',
    'alert-dialog/index': 'src/feedback/alert-dialog/index.ts',
    'breadcrumb/index': 'src/navigation/breadcrumb/index.ts',
    'color-picker/index': 'src/forms/color-picker/index.ts',
    'rating/index': 'src/forms/rating/index.ts',
    'static-rating/index': 'src/data-display/static-rating/index.ts',
    'file-upload/index': 'src/forms/file-upload/index.ts',
    'image-upload/index': 'src/forms/image-upload/index.ts',
    'slider/index': 'src/forms/slider/index.ts',
    'field/index': 'src/forms/field/index.ts',
    'textarea/index': 'src/forms/textarea/index.ts',
    'password-field/index': 'src/forms/password-field/index.ts',
    'password-strength-indicator/index': 'src/forms/password-strength-indicator/index.ts',
    'search-field/index': 'src/forms/search-field/index.ts',
    'email-field/index': 'src/forms/email-field/index.ts',
    'url-field/index': 'src/forms/url-field/index.ts',
    'tel-field/index': 'src/forms/tel-field/index.ts',
    'number-input/index': 'src/forms/number-input/index.ts',
    'checkbox-group/index': 'src/forms/checkbox-group/index.ts',
    'toggle/index': 'src/forms/toggle/index.ts',
    'toggle-group/index': 'src/forms/toggle-group/index.ts',
    'segmented-control/index': 'src/forms/segmented-control/index.ts',
    'collapsible/index': 'src/data-display/collapsible/index.ts',
    'otp-input/index': 'src/forms/otp-input/index.ts',
    'header/index': 'src/layout/header/index.ts',
    'footer/index': 'src/layout/footer/index.ts',
    'sidebar/index': 'src/navigation/sidebar/index.ts',
    'navbar/index': 'src/navigation/navbar/index.ts',
    'main/index': 'src/layout/main/index.ts',
    'section/index': 'src/layout/section/index.ts',
    'surface/index': 'src/layout/surface/index.ts',
    'paper/index': 'src/layout/paper/index.ts',
    'text/index': 'src/typography/text/index.ts',
    'heading/index': 'src/typography/heading/index.ts',
    'code/index': 'src/typography/code/index.ts',
    'blockquote/index': 'src/typography/blockquote/index.ts',
    'kbd/index': 'src/typography/kbd/index.ts',
    'kbd-shortcut/index': 'src/typography/kbd-shortcut/index.ts',
    'icon-button/index': 'src/actions/icon-button/index.ts',
    'button-group/index': 'src/actions/button-group/index.ts',
    'split-button/index': 'src/actions/split-button/index.ts',
    'fab/index': 'src/actions/fab/index.ts',
    'avatar-group/index': 'src/data-display/avatar-group/index.ts',
    'chip/index': 'src/data-display/chip/index.ts',
    'filter-bar/index': 'src/data-display/filter-bar/index.ts',
    'tag/index': 'src/data-display/tag/index.ts',
    'stat/index': 'src/data-display/stat/index.ts',
    'sparkline/index': 'src/data-display/sparkline/index.ts',
    'video/index': 'src/media/video/index.ts',
    'audio/index': 'src/media/audio/index.ts',
    'list/index': 'src/data-display/list/index.ts',
    'description-list/index': 'src/data-display/description-list/index.ts',
    'data-grid/index': 'src/data-display/data-grid/index.ts',
    'virtual-list/index': 'src/data-display/virtual-list/index.ts',
    'swipeable-cards/index': 'src/drag-and-drop/swipeable-cards/index.ts',
    'tree-table/index': 'src/data-display/tree-table/index.ts',
    'calendar/index': 'src/forms/calendar/index.ts',
    'date-picker/index': 'src/forms/date-picker/index.ts',
    'date-range-picker/index': 'src/forms/date-range-picker/index.ts',
    'time-picker/index': 'src/forms/time-picker/index.ts',
    'multi-select/index': 'src/forms/multi-select/index.ts',
    'timeline/index': 'src/data-display/timeline/index.ts',
    'sheet/index': 'src/overlays/sheet/index.ts',
    'code-block/index': 'src/typography/code-block/index.ts',
    'markdown/index': 'src/typography/markdown/index.ts',
    'circular-progress/index': 'src/feedback/circular-progress/index.ts',
    'empty-state/index': 'src/data-display/empty-state/index.ts',
    'bottom-nav/index': 'src/navigation/bottom-nav/index.ts',
    'side-nav/index': 'src/navigation/side-nav/index.ts',
    'logo/index': 'src/media/logo/index.ts',
    // Source lives under a category subfolder (see COMPONENT_COVERAGE_AUDIT.md
    // §D) but the entry *key* below controls the output path, so published
    // subpaths stay flat (`@nebula-lab/react-ui/flex`, not `.../layout/flex`) —
    // consistent with every component above regardless of `src/` depth.
    'aspect-ratio/index': 'src/layout/aspect-ratio/index.ts',
    'center/index': 'src/layout/center/index.ts',
    'container/index': 'src/layout/container/index.ts',
    'flex/index': 'src/layout/flex/index.ts',
    'grid/index': 'src/layout/grid/index.ts',
    'hstack/index': 'src/layout/hstack/index.ts',
    'vstack/index': 'src/layout/vstack/index.ts',
    'stack/index': 'src/layout/stack/index.ts',
    'inline/index': 'src/layout/inline/index.ts',
    'wrap/index': 'src/layout/wrap/index.ts',
    'spacer/index': 'src/layout/spacer/index.ts',
    'label/index': 'src/typography/label/index.ts',
    'link/index': 'src/typography/link/index.ts',
    'image/index': 'src/media/image/index.ts',
    'image-preview/index': 'src/media/image-preview/index.ts',
    'native-select/index': 'src/forms/native-select/index.ts',
    'form/index': 'src/forms/form/index.ts',
  },
  format: ['esm'],
  target: 'es2022',
  // See packages/primitives/tsup.config.ts for why dts is generated via a
  // separate `tsc --emitDeclarationOnly` pass instead of tsup's `dts: true`
  // (ERR_WORKER_OUT_OF_MEMORY — https://github.com/egoist/tsup/issues/920).
  dts: false,
  sourcemap: !!options.watch, // maps are dev/debug DX weight only, not needed by consumers; skip them for the real publish build, keep them under `tsup --watch` (this package's `dev` script) for local debugging
  // Same reasoning `packages/headless/tsup.config.ts` documents for its own
  // `splitting: true` — but here the duplication doesn't come from a
  // cross-folder *relative* import (headless's Dialog/AlertDialog case);
  // every one of this package's ~100 entries is genuinely self-contained.
  // It comes from the root barrel (`index.ts`) doing `export * from './X'`
  // for every subpath — so any component that owns its own
  // `React.createContext()` call (`theme-provider`, `multi-select`,
  // `carousel`, `sortable`, `data-table` — confirmed via
  // `grep -rl "React.createContext" src`, none of the others are re-exported
  // from more than their own single entry) is reachable from *two* separate
  // public entry points: its own subpath (`@nebula-lab/react-ui/theme-provider`)
  // and the root barrel (`@nebula-lab/react-ui`). Under `splitting: false` each
  // entry bundles that module fully self-contained, re-running its
  // module-level `createContext()` call separately in both `dist/index.js`
  // and `dist/theme-provider/index.js` — a consumer that imports
  // `ThemeProvider` from one and `useTheme` from the other gets two
  // distinct Context objects and a "must be used within ThemeProvider"
  // runtime error, despite typechecking cleanly (reproduced building
  // `packages/react-ui-blocks`'s `SaasAppHeader`/`ThemeSwitcher` this
  // session — see `BLOCKS_ARCHITECTURE.md` §14). `splitting: true` lets
  // tsup/rollup extract a shared chunk for a module referenced by multiple
  // entries, so there's exactly one `createContext()` call per context,
  // regardless of which public entry point a consumer reaches it through.
  // Regression test: `theme-provider/theme-provider.test.tsx` imports
  // `ThemeProvider`/`useTheme` from the two different entry points
  // deliberately, via the package specifier (not a relative path), so it
  // actually exercises the built `dist/` output this comment describes.
  splitting: true,
  clean: true,
  treeshake: true,
  external: ['react', 'react-dom', '@nebula-lab/hooks', '@nebula-lab/primitives', '@nebula-lab/headless'],
}));
