import { defineConfig } from 'tsup';

// theme.css itself is not a tsup entry — it's generated by tokens/generate.ts
// and copied to dist/ by this package's `build` script (see package.json).
export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'button/index': 'src/button/index.ts',
    'tokens/index': 'src/tokens/index.ts',
    'theme-provider/index': 'src/theme-provider/index.ts',
  },
  format: ['esm', 'cjs'],
  // See packages/primitives/tsup.config.ts for why dts is generated via a
  // separate `tsc --emitDeclarationOnly` pass instead of tsup's `dts: true`
  // (ERR_WORKER_OUT_OF_MEMORY — https://github.com/egoist/tsup/issues/920).
  dts: false,
  sourcemap: true,
  splitting: false,
  clean: true,
  treeshake: true,
  external: ['react', 'react-dom', '@nebula/hooks', '@nebula/primitives'],
});
