import { defineConfig } from 'tsup';

// theme.css itself is not a tsup entry — it's generated by tokens/generate.ts
// and copied to dist/ by this package's `build` script (see package.json).
export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'button/index': 'src/button/index.ts',
    'input/index': 'src/input/index.ts',
    'card/index': 'src/card/index.ts',
    'badge/index': 'src/badge/index.ts',
    'avatar/index': 'src/avatar/index.ts',
    'separator/index': 'src/separator/index.ts',
    'accordion/index': 'src/accordion/index.ts',
    'dialog/index': 'src/dialog/index.ts',
    'popover/index': 'src/popover/index.ts',
    'tooltip/index': 'src/tooltip/index.ts',
    'tabs/index': 'src/tabs/index.ts',
    'checkbox/index': 'src/checkbox/index.ts',
    'switch/index': 'src/switch/index.ts',
    'radio-group/index': 'src/radio-group/index.ts',
    'progress/index': 'src/progress/index.ts',
    'spinner/index': 'src/spinner/index.ts',
    'skeleton/index': 'src/skeleton/index.ts',
    'tokens/index': 'src/tokens/index.ts',
    'theme-provider/index': 'src/theme-provider/index.ts',
    'pagination/index': 'src/pagination/index.ts',
    'stepper/index': 'src/stepper/index.ts',
    'tree/index': 'src/tree/index.ts',
    'navigation-menu/index': 'src/navigation-menu/index.ts',
    'drawer/index': 'src/drawer/index.ts',
    'hover-card/index': 'src/hover-card/index.ts',
    'toast/index': 'src/toast/index.ts',
    'tree-view/index': 'src/tree-view/index.ts',
    'command/index': 'src/command/index.ts',
    'carousel/index': 'src/carousel/index.ts',
    'data-table/index': 'src/data-table/index.ts',
    'draggable/index': 'src/draggable/index.ts',
    'droppable/index': 'src/droppable/index.ts',
    'sortable/index': 'src/sortable/index.ts',
  },
  format: ['esm'],
  target: 'es2022',
  // See packages/primitives/tsup.config.ts for why dts is generated via a
  // separate `tsc --emitDeclarationOnly` pass instead of tsup's `dts: true`
  // (ERR_WORKER_OUT_OF_MEMORY — https://github.com/egoist/tsup/issues/920).
  dts: false,
  sourcemap: true,
  splitting: false,
  clean: true,
  treeshake: true,
  external: ['react', 'react-dom', '@nebula/hooks', '@nebula/primitives', '@nebula/styleless'],
});
